apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autobrr-config
  namespace: autobrr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem