apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: bazarr
spec:
  selector:
    matchLabels:
      app: bazarr
  replicas: 1
  template:
    metadata:
      labels:
        app: bazarr
        deployed_by: argocd
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: "TZ"
              value: "Europe/Paris"
          ports:
            - containerPort: 6767
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
          - mountPath: /config
            name: bazarr-config
          - mountPath: /tv
            name: bazarr-series
          - mountPath: /movies
            name: bazarr-movies
      volumes:
      - persistentVolumeClaim:
          claimName: bazarr-config
        name: bazarr-config
      - persistentVolumeClaim:
          claimName: bazarr-series
        name: bazarr-series
      - persistentVolumeClaim:
          claimName: bazarr-movies
        name: bazarr-movies