apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: bazarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-series
  namespace: bazarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  storageClassName: freenas-nfs-csi-pool1
  volumeMode: Filesystem
  volumeName: bazarr-series
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-movies
  namespace: bazarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  storageClassName: freenas-nfs-csi-pool1
  volumeMode: Filesystem
  volumeName: bazarr-movies
