apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-series
  namespace: jellyfin
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  storageClassName: freenas-nfs-csi-pool1
  volumeMode: Filesystem
  volumeName: jellyfin-series
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-movies
  namespace: jellyfin
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  storageClassName: freenas-nfs-csi-pool1
  volumeMode: Filesystem
  volumeName: jellyfin-movies