apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  sources:
  - repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: v0.28.1
    helm:
      valueFiles:
      - $values/kubernetes/argocd/values/vault/values.yaml
  - repoURL: 'https://github.com/SoulKyu/my-homelab.git'
    ref: values
    targetRevision: main