apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  sources:
  - repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: 1.16.1
    helm:
      valueFiles:
      - $values/kubernetes/argocd/values/cert-manager/values.yaml
  - repoURL: 'https://github.com/SoulKyu/my-homelab.git'
    ref: values
    targetRevision: main