apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  sources:
  - chart: vault-secrets-webhook
    repoURL: ghcr.io/bank-vaults/helm-charts
    targetRevision: 1.21.3
    helm:
      valueFiles:
      - $values/kubernetes/argocd/values/vault-secrets-webhook/values.yaml
  - repoURL: 'https://github.com/SoulKyu/my-homelab.git'
    ref: values
    targetRevision: main