apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volumes
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: volumes
  sources:
  - repoURL: 'https://github.com/SoulKyu/my-homelab.git'
    path: kubernetes/argocd/values/volumes
    targetRevision: main