apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scaleway-ddns
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: scalewayddns
  sources:
  - repoURL: 'https://github.com/SoulKyu/my-homelab.git'
    path: scaleway-ddns
    targetRevision: main