apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: radarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies
  namespace: radarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  storageClassName: freenas-nfs-csi-pool1
  volumeMode: Filesystem
  volumeName: radarr-movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-downloads
  namespace: radarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  storageClassName: freenas-nfs-csi-pool1
  volumeMode: Filesystem
  volumeName: radarr-downloads