apiVersion: v1
kind: Secret
metadata:
  name: scalewayddns
  namespace: scalewayddns
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.local.soulkyu.net:443"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
type: Opaque
stringData:
  scaleway-ddns.yaml: |
    scaleway:
      project_id: ${vault:secrets/data/scaleway#project_id}
      access_key: ${vault:secrets/data/scaleway#access_key}
      secret_key: ${vault:secrets/data/scaleway#secret_key}

    domain:
      name: soulkyu.net
      record: "*.public"
      ttl: 60

    interval: 300

    ipv4:
      enabled: true
      url: http://api-ipv4.ip.sb

    ipv6:
      enabled: false
      url: https://api-ipv6.ip.sb/ip