# Password : qbittorrent123*qbittorrent
# Key : UkBarc3hsGzOZMgk85tKi8CnaiMIY7sxoyobLqy4aAU=
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  selector:
    matchLabels:
      app: qbittorrent
  replicas: 1
  template:
    metadata:
      labels:
        app: qbittorrent
        deployed_by: argocd
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers: 
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: "TZ"
              value: "Europe/Paris"
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - containerPort: 8080
            - containerPort: 6881
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
          - mountPath: /config
            name: qbittorrent-config
          - mountPath: /downloads
            name: qbittorrent-downloads
      volumes:
      - persistentVolumeClaim:
          claimName: qbittorrent-config
        name: qbittorrent-config
      - persistentVolumeClaim:
          claimName: qbittorrent-downloads
        name: qbittorrent-downloads
