# Password : qbittorrent123*qbittorrent
# Key : UkBarc3hsGzOZMgk85tKi8CnaiMIY7sxoyobLqy4aAU=
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  selector:
    matchLabels:
      app: qbittorrent
  replicas: 1
  template:
    metadata:
      labels:
        app: qbittorrent
        deployed_by: argocd
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker04.local.soulkyu.net
        kubernetes.io/os: linux
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 9.9.9.9
      containers:
        - name: gluetun-ivpn
          image: qmcgaw/gluetun:latest
          env:
           # If you having connection issues, try enabling these variables to help diagnose it.
           # - name: FIREWALL_DEBUG
           #   value: "on"
           # - name: FIREWALL_INPUT_PORTS
           #   value: "8080"
            - name: HEALTH_TARGET_ADDRESS
              value: 127.0.0.1:8080
            - name: EXTRA_SUBNETS
              value: 10.0.0.0/8
            - name: FIREWALL_INPUT_PORTS
              value: "8080,6881"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: 10.0.0.0/8
            - name: FIREWALL_INBOUND_SUBNETS
              value: 10.0.0.0/8
            - name: VPN_SERVICE_PROVIDER
              value: ivpn
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_PRIVATE_KEY
              value: WJAGsC1TQCUGMpEtWsBpKs345UEHrxToXu4Z1rxPgH8=
            - name: WIREGUARD_ADDRESSES
              value: 172.22.121.9/32
            - name: SERVER_COUNTRIES
              value: switzerland
            - name: SERVER_CITIES
              value: zurich
            - name: SERVER_HOSTNAMES
              value: ch3.wg.ivpn.net
            - name: VPN_ENDPOINT_PORT
              value: "2049"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: VPN_PORT_FORWARDING_PROVIDER
              value: "protonvpn"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "44053"
          securityContext:                          
            privileged: true                        
            capabilities:                           
              add:                                  
                - NET_ADMIN
          ports:                                    
            - containerPort: 8888                   
            - containerPort: 8388                   
            - containerPort: 8388                   
              protocol: UDP                         
            - containerPort: 8000      
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: "TZ"
              value: "Europe/Paris"
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - containerPort: 8080
            - containerPort: 6881
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
          - mountPath: /config
            name: qbittorrent-config
          - mountPath: /downloads
            name: qbittorrent-downloads
      volumes:
      - persistentVolumeClaim:
          claimName: qbittorrent-config
        name: qbittorrent-config
      - persistentVolumeClaim:
          claimName: qbittorrent-downloads
        name: qbittorrent-downloads