apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-wireguard
data:
  VPN_SERVICE_PROVIDER: vault:secrets/data/wireguard#VPN_SERVICE_PROVIDER
  VPN_TYPE: vault:secrets/data/wireguard#VPN_TYPE
  WIREGUARD_PRIVATE_KEY: vault:secrets/data/wireguard#WIREGUARD_PRIVATE_KEY
  WIREGUARD_ADDRESSES: vault:secrets/data/wireguard#WIREGUARD_ADDRESSES
  SERVER_COUNTRIES: vault:secrets/data/wireguard#SERVER_COUNTRIES
  SERVER_CITIES: vault:secrets/data/wireguard#SERVER_CITIES
  SERVER_HOSTNAMES: vault:secrets/data/wireguard#SERVER_HOSTNAMES
  VPN_ENDPOINT_PORT: vault:secrets/data/wireguard#VPN_ENDPOINT_PORT
  VPN_PORT_FORWARDING: vault:secrets/data/wireguard#VPN_PORT_FORWARDING
  VPN_PORT_FORWARDING_PROVIDER: vault:secrets/data/wireguard#VPN_PORT_FORWARDING_PROVIDER
type: Opaque
