apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-wireguard
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.local.soulkyu.net:443"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
stringData:
  VPN_SERVICE_PROVIDER: "vault:secrets/data/wireguard#VPN_SERVICE_PROVIDER"
  VPN_TYPE: "vault:secrets/data/wireguard#VPN_TYPE"
  WIREGUARD_PRIVATE_KEY: "vault:secrets/data/wireguard#WIREGUARD_PRIVATE_KEY"
  WIREGUARD_ADDRESSES: "vault:secrets/data/wireguard#WIREGUARD_ADDRESSES"
  SERVER_COUNTRIES: "vault:secrets/data/wireguard#SERVER_COUNTRIES"
  SERVER_CITIES: "vault:secrets/data/wireguard#SERVER_CITIES"
  SERVER_HOSTNAMES: "vault:secrets/data/wireguard#SERVER_HOSTNAMES"
  WIREGUARD_ENDPOINT_PORT: "vault:secrets/data/wireguard#VPN_ENDPOINT_PORT"
  DNS_ADDRESS: "vault:secrets/data/wireguard#DNS_ADDRESS"
type: Opaque
