# Password : qbittorrent123*qbittorrent
# Key : UkBarc3hsGzOZMgk85tKi8CnaiMIY7sxoyobLqy4aAU=
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  selector:
    matchLabels:
      app: qbittorrent
  replicas: 1
  template:
    metadata:
      labels:
        app: qbittorrent
        deployed_by: argocd
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      initContainers:
        - name: gluetun-ivpn
          restartPolicy: Always
          image: qmcgaw/gluetun:latest
          env:
           # If you having connection issues, try enabling these variables to help diagnose it.
           # - name: FIREWALL_DEBUG
           #   value: "on"
           # - name: FIREWALL_INPUT_PORTS
           #   value: "8080"
            - name: TZ
              value: 'UTC'
            - name: HEALTH_TARGET_ADDRESS
              value: 127.0.0.1:8080
            - name: EXTRA_SUBNETS
              value: 10.0.0.0/8
            - name: FIREWALL_INPUT_PORTS
              value: "8080,6881"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
            - name: FIREWALL_INBOUND_SUBNETS
              value: 10.0.0.0/8
          envFrom:
            - secretRef:
                name: qbittorrent-wireguard
          securityContext:                          
            privileged: true                        
            capabilities:                           
              add:                                  
                - NET_ADMIN
                - SYS_MODULE
          ports:                                    
            - containerPort: 8888                   
            - containerPort: 8388                   
            - containerPort: 8388                   
              protocol: UDP                         
            - containerPort: 8000
        - name: ping
          image: busybox
          command:
              - sh
              - -c
              - |
                  while ! ping -c 1 8.8.8.8; do
                    echo "Ping failed, retrying in 5"
                    sleep 5
                  done
                  echo "ping successful, exiting"
      containers: 
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: "TZ"
              value: "Europe/Paris"
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - containerPort: 8080
            - containerPort: 6881
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
          - mountPath: /config
            name: qbittorrent-config
          - mountPath: /downloads
            name: qbittorrent-downloads
      volumes:
      - persistentVolumeClaim:
          claimName: qbittorrent-config
        name: qbittorrent-config
      - persistentVolumeClaim:
          claimName: qbittorrent-downloads
        name: qbittorrent-downloads