apiVersion: v1
stringData:
  driver-config-file.yaml: | 
    driver: freenas-nfs
    httpConnection:
      allowInsecure: true
      host: 192.168.1.200
      password: ${vault:secrets/data/truenas#password}
      port: 80
      protocol: http
      username: ${vault:secrets/data/truenas#user}
    instance_id: truenas
    nfs:
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareHost: 192.168.1.200
      shareMapallGroup: ""
      shareMapallUser: ""
      shareMaprootGroup: admin
      shareMaprootUser: admin
    sshConnection:
      host: 192.168.1.200
      password: ${vault:secrets/data/truenas#password}
      port: 22
      username: ${vault:secrets/data/truenas#user}
    zfs:
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetParentName: POOL1/k8s/vols
      datasetPermissionsGroup: 0
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      detachedSnapshotsDatasetParentName: POOL1/k8s/snaps
kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.local.soulkyu.net:443"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
  name: zfs-nfs-democratic-csi-driver-config
  namespace: democratic-csi
type: Opaque