apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: sonarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-series
  namespace: sonarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  storageClassName: freenas-nfs-csi-pool1
  volumeMode: Filesystem
  volumeName: sonarr-series
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads
  namespace: sonarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  storageClassName: freenas-nfs-csi-pool1
  volumeName: sonarr-downloads
  volumeMode: Filesystem